version: '3.1'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - /databases:/var/lib/postgresql/data/:rw
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/

  adminer:
    image: adminer:4.8.0
    ports:
      - 8080:8080
    restart: always
